### ISSUE TITLE
Google Play Games login not possible

### ISSUE THREAD

**Issue by Traumlewis** [davidramiro/gpay-gms-patch#1]
DE: Der in-game Login ist nicht möglich. Es lädt aber nichts tut sich.

Google Translate EN: The in-game login is not possible. It loads but nothing happens.

**Comment by davidramiro** [comment]
In-game login? What exactly do you mean by that? This script would not interfere with Google Play Games in any way, or are you referring to in game payment?

**Comment by Traumlewis** [comment]
Apparently, if I delete the cache from GMS Services it will work. But Google Pay will not work anymore :(

https://i.imgur.com/sSd1sUn_d.jpg?maxwidth=640&shape=thumb&fidelity=medium

**Comment by davidramiro** [comment]
Seems like you're running MIUI - which version exactly? Android Q?

**Comment by Traumlewis** [comment]
MIUI.EU, MIMix3 10.3.3, Android 9

**Comment by davidramiro** [comment]
Hm, just tried logging into Google Play Games on a Mi9, also xiaomi.eu, although 10.5, and it worked fine. Don't know if an update of xiaomi.eu would help but I can't reproduce this issue at all.
